### ISSUE TITLE
Can not Sum on a child aggregation if group on aggregation

### ISSUE THREAD

**Issue by ethanli83** [ethanli83/EFSqlTranslator#14]
Query:
<pre>db.Employees
	.GroupBy(e => e.Orders.Count())
    .Select(g => new { g.Key, Sum = g.Sum(e => e.Orders.Count()) })</pre>

Error:
<pre>Nancy.RequestExecutionException: Oh noes! ---&lt; System.InvalidCastException: Unable to cast object of type 'EFSqlTranslator.Translation.DbObjects.DbReference' to type 'EFSqlTranslator.Translation.DbObjects.IDbSelect'.
   at EFSqlTranslator.Translation.MethodTranslators.AggregationTranslatorBase.CreateAggregation(MethodCallExpression m, TranslationState state, UniqueNameGenerator nameGenerator, IDbSelect childSelect, IDbFunc dbFunc)
   at EFSqlTranslator.Translation.MethodTranslators.CountTranslator.Translate(MethodCallExpression m, TranslationState state, UniqueNameGenerator nameGenerator)
   at EFSqlTranslator.Translation.TranslationPlugIns.TranslateMethodCall(MethodCallExpression m, TranslationState state, UniqueNameGenerator nameGenerator)
   at EFSqlTranslator.Translation.LinqTranslator.VisitMethodCall(MethodCallExpression m)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at EFSqlTranslator.Translation.LinqTranslator.VisitLambda[T](Expression`1 l)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at EFSqlTranslator.Translation.LinqTranslator.VistMethodArguments(Expression[] args)
   at EFSqlTranslator.Translation.LinqTranslator.VisitMethodCall(MethodCallExpression m)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at EFSqlTranslator.Translation.LinqTranslator.VisitNew(NewExpression n)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at EFSqlTranslator.Translation.LinqTranslator.VisitLambda[T](Expression`1 l)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at EFSqlTranslator.Translation.LinqTranslator.VistMethodArguments(Expression[] args)
   at EFSqlTranslator.Translation.LinqTranslator.VisitMethodCall(MethodCallExpression m)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at EFSqlTranslator.Translation.LinqTranslator.Visit(Expression e)
   at EFSqlTranslator.Translation.LinqTranslator.Translate(Expression exp, IModelInfoProvider infoProvider, IDbObjectFactory dbFactory)
   at LinqRunner.Server.Api.DbContextExtensions.Query(DbContext db, IQueryable query, String& sql) in /Users/ethanli/Projects/LinqRunner/LinqRunner.Server/Api/DbContextExtensions.cs:line 34
   at Submission#2.&gt;&gt;Initialize&lt;&lt;d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.&gt;RunSubmissionsAsync&lt;d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Scripting.Script`1.&gt;RunSubmissionsAsync&lt;d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LinqRunner.Server.Api.LinqRunner.&gt;RunAsync&lt;d__3`1.MoveNext() in /Users/ethanli/Projects/LinqRunner/LinqRunner.Server/Api/LinqRunner.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LinqRunner.Server.Api.RunnerApi.&gt;RunLinq&lt;d__2.MoveNext() in /Users/ethanli/Projects/LinqRunner/LinqRunner.Server/Api/RunnerApi.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at LinqRunner.Server.Api.RunnerApi.&gt;&lt;c__DisplayClass1_0.&gt;&gt;-ctor&lt;b__1&lt;d.MoveNext() in /Users/ethanli/Projects/LinqRunner/LinqRunner.Server/Api/RunnerApi.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRouteInvoker.&gt;Invoke&lt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.Routing.DefaultRequestDispatcher.&gt;Dispatch&lt;d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nancy.NancyEngine.&gt;InvokeRequestLifeCycle&lt;d__22.MoveNext()
   --- End of inner exception stack trace ---
   at Nancy.NancyEngine.InvokeOnErrorHook(NancyContext context, ErrorPipeline pipeline, Exception ex)</pre>

**Comment by ethanli83** [comment]
Fix
