### ISSUE TITLE
Two consequent queries fail (at least with SQL Server)

### ISSUE THREAD

**Issue by Shaddix** [ethanli83/EFSqlTranslator#34]
In Console app if we do like:

```
var result = db.Query(query, new EFModelInfoProvider(db), new SqlObjectFactory(), out sql);
var result2 = db.Query(query, new EFModelInfoProvider(db), new SqlObjectFactory(), out sql);

```
It fails on  a second query with
```

System.InvalidOperationException: The ConnectionString property has not been initialized.
   at System.Data.SqlClient.SqlConnection.PermissionDemand()
   at System.Data.SqlClient.SqlConnectionFactory.PermissionDemand(DbConnection outerConnection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at EFSqlTranslator.Translation.LinqExecutor`1.Execute() in D:\\Work\\EFSqlTranslator\\EFSqlTranslator.Translation\\LinqExecutor.cs:line 29
   at EFSqlTranslator.Translation.Extensions.DbContextExtensions.Query[T
](DbContext db, IQueryable`1 query, IModelInfoProvider infoProvider, IDbObjectFactory factory, String& sql) in D:\\Work\\EFSqlTranslator\\EFSqlTranslator.Translation\\Extensions\\DbContextExtensions.cs:line 39
   at EFSqlTranslator.ConsoleApp.Program.Main(String[] args) in D:\\Work\\EFSqlTranslator\\EFSqlTranslator.ConsoleApp\\Program.cs:line 54"
```

For me it seems that ```_dtx.Database.GetDbConnection()``` should not be wrapped in using, and the connection should be opened only if it's not already opened.
Are you ok with removing ``using``?

Another use-cases: 
- Execute some EF query via EF itself, then do another query on the same context via EFSqlTranslator. Same issue
- Execute EFSqlTranslator query and then execute a normal EF query. EF query fails, because the connection is closed/disposed

**Comment by ethanli83** [comment]
@Shaddix,

I won't mind to remove the "using"
